---
- name: iis configuration
  hosts: all
  gather_facts: no

  tasks:
    - name: enable features
      win_feature:
        name: "{{ win_features }}"
        state: present
        include_sub_features: yes
        include_management_tools: yes
      register: win_output

    - name: reboot server if required
      win_reboot:
      when: win_output.reboot_required

    - name: Create a new application pool in 'Started' state
      community.windows.win_iis_webapppool:
        name: "{{ item.value.name }}"
        state: "{{ item.value.state }}"
        attributes:
          managedPipelineMode: "{{ item.value.pipeline_mode }}"
          managedRuntimeVersion: "{{ item.value.runtime_version }}"
          processModel.maxProcesses: "{{ item.value.max_processes }}"
      loop: "{{ app_pools | dict2items }}"

    - name: Ensure directories are present
      win_file:
        path: '{{ dir_path }}{{ item.0.name }}\{{ item.1 }}'
        state: directory
      loop: "{{ app_pools | json_query('*') | product(apps) | list}}"

    - name: Create a virtual directory if it does not exist
      community.windows.win_iis_virtualdirectory:
        name: '{{ item.1 }}'
        site: "{{ iis_site }}"
        application: "{{ item.1 }}"
        state: present
        physical_path: '{{ dir_path }}{{ item.0.name }}\{{ item.1 }}'
      loop: "{{ app_pools | json_query('*') | product(template_apps) | list}}"
      tags: create_vdir

    - name: Create a virtual directory if it does not exist
      community.windows.win_iis_virtualdirectory:
        name: c2formweb
        site: "{{ iis_site }}"
        application: c2formweb
        state: absent
        physical_path: '{{ dir_path }}payrollportal\c2formweb'
      tags: delete_vdir
    # - name: Delete virtual directory
    #   community.windows.win_iis_virtualdirectory:
    #     name: "{{ item.1 }}"
    #     site: "{{ iis_site }}"
    #     application: "{{ item.1 }}"
    #     state: absent
    #     physical_path: '{{ dir_path }}{{ item.0.name }}\{{ item.1 }}'
    #   loop: "{{ app_pools | json_query('*') | product(apps) | list}}"
    #   tags: delete_vdir

    - name: Configure webapplication on IIS (specific_user)
      community.windows.win_iis_webapplication:
        name: "{{ item.1 }}"
        site: "{{ iis_site }}"
        state: present
        username: "{{ iis_username }}"
        password: "{{ iis_password }}"
        physical_path: '{{ dir_path }}{{ item.0.name }}\{{ item.1 }}'
        connect_as: "{{ connect_as | default('pass_through')}}"
        application_pool: "{{ item.0.name }}"
      loop: "{{ app_pools | json_query('*') | product(apps) | list}}"
      tags: create_app

    # - name: Delete webapplication on IIS (specific_user)
    #   community.windows.win_iis_webapplication:
    #     name: "{{ item.1 }}"
    #     site: "{{ iis_site }}"
    #     state: absent
    #     username: "{{ iis_username }}"
    #     password: "{{ iis_password }}"
    #     physical_path: '{{ dir_path }}{{ item.0.name }}\{{ item.1 }}'
    #     connect_as: "{{ connect_as | default('pass_through')}}"
    #     applicationpool: "{{ item.0.name }}"
    #   loop: "{{ app_pools | json_query('*') | product(apps) | list}}"
    #   tags: delete_app

    - name: template website
      include_tasks: website_tasks.yaml
      args:
        apply:
          tags:
            - template
      loop: "{{ app_pools | json_query('*') | product(template_apps) | list}}"
      tags: template

    - name: win shell
      win_command: "{{ cli_command }}"
      when: cli_command is defined

    - name: run script
      win_shell: "{{ shell_command }}"
      when: shell_command is defined
