---
- name: iis tag check
  hosts: all
  gather_facts: no

  tasks:
    - name: Fail due to no tags
      fail:
        msg: "You must provide a tag of either create or delete"

- name: iis configuration
  hosts: all
  gather_facts: no
  tags: configure

  tasks:
    - name: enable features
      ansible.windows.win_feature:
        name: "{{ win_features }}"
        state: present
        include_sub_features: yes
        include_management_tools: yes
      register: win_output

    - name: reboot server if required
      ansible.windows.win_reboot:
      when: win_output.reboot_required

    - name: Create the application pool(s)
      community.windows.win_iis_webapppool:
        name: "{{ item.key }}"
        state: "{{ item.value.state }}"
        attributes:
          managedPipelineMode: "{{ item.value.pipeline_mode }}"
          managedRuntimeVersion: "{{ item.value.runtime_version }}"
          processModel.maxProcesses: "{{ item.value.max_processes }}"
      loop: "{{ app_pools | dict2items }}"

    - name: Ensure directories are present
      ansible.windows.win_file:
        path: '{{ dir_path }}{{ item.value.pool }}\{{ item.key }}'
        state: directory
      loop: "{{ dictionary_apps | dict2items }}"

    - name: Ensure virtual directories are present
      community.windows.win_iis_virtualdirectory:
        name: '{{ item.key }}'
        site: "{{ iis_site }}"
        application: "{{ item.key }}"
        state: "{{ item.value.state }}"
        physical_path: '{{ dir_path }}{{ item.value.pool }}\{{ item.key }}'
      loop: "{{ dictionary_apps | dict2items }}"

    - name: Configure webapplication on IIS (specific_user)
      community.windows.win_iis_webapplication:
        name: "{{ item.key }}"
        site: "{{ iis_site }}"
        state: "{{ item.value.state }}"
        username: "{{ iis_username }}"
        password: "{{ iis_password }}"
        physical_path: '{{ dir_path }}{{ item.value.pool }}\{{ item.key }}'
        connect_as: "{{ connect_as | default('pass_through')}}"
        application_pool: "{{ item.value.pool }}"
      loop: "{{ dictionary_apps | dict2items }}"

    - name: template website
      include_tasks: website_tasks.yaml
      args:
        apply:
          tags:
            - template
      loop: "{{ dictionary_apps | dict2items}}"
      tags: template

    - name: win shell
      ansible.windows.win_command: "{{ cli_command }}"
      when: cli_command is defined

    - name: run script
      ansible.windows.win_shell: "{{ shell_command }}"
      when: shell_command is defined

- name: iis delete all configurations
  hosts: all
  gather_facts: no
  tags: delete

  tasks:
    - name: delete block
      block:
      - name: Delete webapplication on IIS (specific_user)
        community.windows.win_iis_webapplication:
          name: "{{ item.key }}"
          site: "{{ iis_site }}"
          state: absent
          username: "{{ iis_username }}"
          password: "{{ iis_password }}"
          physical_path: '{{ dir_path }}{{ item.value.pool }}\{{ item.key }}'
          connect_as: "{{ connect_as | default('pass_through')}}"
          applicationpool: "{{ item.value.pool }}"
        loop: "{{ dictionary_apps | dict2items }}"
        tags: delete

      - name: Remove virtual directories
        win_shell: Remove-Item -LiteralPath {{ dir_path }}{{ item.value.pool }}\{{ item.key }} -Recurse -Force
        loop: "{{ dictionary_apps | dict2items }}"
        tags: delete
        ignore_errors: yes
      tags: delete