---
- name: iis configuration
  hosts: all

  tasks:
    - name: enable features
      win_feature:
        name: "{{ win_features }}"
        state: present
        include_sub_features: yes
        include_management_tools: yes
      register: win_output

    - name: reboot server if required
      win_reboot:
      when: win_output.reboot_required

    - name: Create a new application pool in 'Started' state
      win_iis_webapppool:
        name: "{{ item.value.name }}"
        state: "{{ item.value.state }}"
      loop: "{{ app_pools | dict2items }}"

    - name: Configure webapplication on IIS (specific_user)
      win_iis_webapplication:
        name: "{{ item.value.name }}"
        site: "{{ iis_site }}"
        state: "{{ item.value.state }}"
        username: "{{ iis_username }}"
        password: "{{ iis_password }}"
        connect_as: "{{ connect_as | default('pass_through')}}"
      loop: "{{ app_pools | dict2items }}"

    - name: Ensure directories are present
      win_file:
        path: "{{ dir_path }}{{item}}"
        state: directory
      loop: "{{ apps }}"

    - name: Create a virtual directory if it does not exist
      win_iis_virtualdirectory:
        name: "{{ item }}"
        site: "{{ iis_site }}"
        state: present
        physical_path: "{{ dir_path }}{{item}}"
      loop: "{{ apps }}"

    - name: DOE IIS site
      win_iis_website:
        name: "{{ item }}"
        state: started
        application_pool: "{{app_pool}}"
        physical_path: "{{ dir_path }}{{ item }}"
      loop: "{{ apps }}"

    - name: win shell
      win_command: "{{ cli_command }}"
      when: cli_command is defined

    - name: run script
      win_shell: "{{ shell_command }}"
      when: shell_command is defined
