---
- name: iis tag check
  hosts: all
  gather_facts: no

  tasks:
    - name: Configure webapplication on IIS (specific_user)
      community.windows.win_iis_webapplication:
        name: applicationmailweb
        site: "{{ iis_site }}"
        state: present
        username: "{{ iis_username }}"
        password: "{{ iis_password }}"
        physical_path: 'c:\inetpub\wwwroot\payrollportal\applicationmailweb'
        connect_as: specific_user
        application_pool: payrollportal2.0