---
- name: iis tag check
  hosts: all
  gather_facts: no

  tasks:
    - name: Ensure directories are present
      ansible.windows.win_file:
        path: 'c:\inetpub\wwwroot\payrollportal\pepper'
        state: directory

    - name: Ensure virtual directories are present
      community.windows.win_iis_virtualdirectory:
        name: pepper
        site: "{{ iis_site }}"
        application: applicationmailweb
        state: present
        physical_path: 'c:\inetpub\wwwroot\payrollportal\pepper'

    - name: Configure webapplication on IIS (specific_user)
      community.windows.win_iis_webapplication:
        name: applicationmailweb
        site: "{{ iis_site }}"
        state: present
        username: "{{ iis_username }}"
        password: "{{ iis_password }}"
        physical_path: 'c:\inetpub\wwwroot\payrollportal\pepper'
        connect_as: "{{ connect_as | default('pass_through')}}"
        application_pool: "payrollportal"