---
- name: Deploy VM from template
  hosts: localhost
  become: no

  vars:
    win_template: vRA_DIIT_WIN2016D_Template_Dec_2021

  tasks:
    - name: Create a virtual machine from a template
      vmware_guest:
        # hostname: "{{ vcenter_hostname }}"
        # username: "{{ vcenter_username }}"
        # password: "{{ vcenter_password }}"
        validate_certs: no
        folder: /Ansible
        name: ansible_poc_vm
        state: poweredon
        template: "{{ win_template }}"
        customization_spec: "DIIT_Windows"
        networks:
        - name: NSXPG-172.24.42.0
        customization:
          password: ansible_password
          runonce:
          - powershell.exe -ExecutionPolicy Unrestricted -File C:\Windows\Temp\ConfigureRemotingForAnsible.ps1 -ForceNewSSLCert -EnableCredSSP
        wait_for_customization: yes
        wait_for_ip_address: yes
      delegate_to: localhost
      register: deploy