---
- name: iis configuration
  hosts: all
  gather_facts: no
  tasks:

    - name: template over web files
      win_template:
        src: appname.j2
        dest: files/iis/index.html
      delegate_to: localhost
      loop: "{{ app_pools | json_query('*') | product(template_apps) | list}}"

    - name: Copy over web files
      win_copy:
        src: files/iis/
        dest: '{{ dir_path }}{{item.0.name}}\{{item.1}}'
      loop: "{{ app_pools | json_query('*') | product(template_apps) | list}}"