---
- name: configure virtual directory physical path credentials
  win_shell: |
    Import-Module WebAdministration
    $virtualdirectorypath = '{{iis_path}}{{iis_site}}\{{ item.key }}'
    $username = "{{ item.value.username }}"
    $password = "{{ item.value.password }}"
    Set-ItemProperty -Path $virtualdirectorypath -Name userName -Value $username
    Set-ItemProperty -Path $virtualdirectorypath -Name password -Value $password
  loop: "{{ virt_dirs | dict2items }}"