# Features to enable
win_features:
  - RemoteAccess
  - XPS-Viewer
  - SNMP-Service
  - Web-Mgmt-Tools
  - Web-WHC
  - BITS
  - PowerShellRoot
  - Web-Server

# Connect As (specific_user | pass_through)
# If not defined, task will run as pass_through
connect_as: specific_user

# iis definition(s)
iis_username: TestUser1
iis_password: TestPassword
iis_site: "Default Web Site"

# base directory path
dir_path: 'c:\inetpub\wwwroot\'

# App pool defintion(s)
app_pools:
  payrollportal:
    state: present
    pipeline_mode: Integrated
    runtime_version: v4.0
    max_processes: 1
  payrollportal2.0:
    state: present
    pipeline_mode: Integrated
    runtime_version: v2.0
    max_processes: 1

# Application definitions
dictionary_apps:
  applicationmailweb:
    pool: payrollportal
    state: present
  aprlaccessweb:
    pool: payrollportal2.0
    state: present
  aspnet_client:
    pool: payrollportal
    state: present
  bankaccountrequestweb:
    pool: payrollportal
    state: present
  c2formweb:
    pool: payrollportal2.0
    state: present


# List of Apps
apps: [ "applicationmailweb", "aprlaccessweb", "aspnet_client",
"bankaccountrequestweb", "c2formweb", "collegesavingsweb", "common", "configuration",
"configuration2.2.6", "cpsaccessweb", "depositweb", "directdepositcorrectionsweb",
"eftmobile", "eftreversalweb", "eftstoppayment", "eftstoppaymentweb",
"empsalaryadjustmentweb", "eftweb", "epiweb", "help", "inquirytrackingmobile", "offline",
"overtimerequestweb", "overtimewaiverweb", "payrollissueweb", "payrollissuewebext",
"payrollportalmobile", "payrollportalweb", "payrollregistermobile", "payrollsecurityweb",
"portalreportingweb", "pp", "relieffund", "requestforverificationweb",
"salarydiffstepweb", "savingbondsweb", "services", "settings", "trainingsessionweb",
"vendorinquirytrackingweb", "video", "vportalbridge", "w2correctionweb", "wageworksweb",
"workerscompensationweb" ]